export { default as Login } from "./Login";
export { default as Home } from "./Home";
export { default as Doctors } from "./Doctors";
export { default as Medicines } from "./Medicines";
export { default as AddDoctor } from "./AddDoctor";
export { default as AddMedicine } from "./AddMedicine";
export { default as EditMedicine } from "./EditMedicine";
export { default as Appointments } from "./Appointments";
export { default as AddOrders } from "./AddOrders";